backend:
  name: github
  repo: tinnguyen03102004/Bio
  branch: main
  # Trỏ tới OAuth Gateway bạn vừa deploy trên Vercel
  base_url: https://netlify-cms-oauth-ten.vercel.app

# Nơi lưu media khớp repo hiện tại
media_folder: "static/uploads"
public_folder: "/uploads"

# (Khuyến nghị) Bật quy trình duyệt bài
publish_mode: editorial_workflow

# Cấu hình slug & định dạng tệp
slug:
  clean_accents: true
  sanitize_replacement: "-"
  encoding: "unicode"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    format: "frontmatter"
    extension: "md"
    # Dùng trường "slug" bạn khai báo để làm định danh file
    identifier_field: "slug"
    # Đường dẫn file (tùy chọn): products/<slug>.md
    path: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Không dấu, dùng `-`" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", min: 0 }
      - { label: "Compare at Price", name: "compare_at_price", widget: "number", required: false }
      - { label: "Buy URL", name: "buy_url", widget: "string" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
      - label: "Attributes"
        name: "attributes"
        widget: "object"
        fields:
          - { label: "Material", name: "material", widget: "string" }
          - { label: "Fit", name: "fit", widget: "string" }
          - { label: "Care", name: "care", widget: "string" }
          - { label: "Made in", name: "made_in", widget: "string" }
      - label: "Variants"
        name: "variants"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "SKU", name: "sku", widget: "string" }
          - { label: "Price", name: "price", widget: "number", value_type: "float", min: 0 }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
